name: Test
on:
  push:
    branches: main
    
jobs:
  dependencies:
    runs-on: ubuntu-latest
    
    steps: 
    - name: checkout code
      uses: actions/checkout@v3

    - name: install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.11.0'
        cache: 'yarn'

    - run: yarn install

  build:
    needs: dependencies
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.11.0'

    - run: yarn install

    - name: build
      run: yarn build
      

  linters:
    needs: dependencies
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.11.0'

    - run: yarn install
    
    - name: start linters
      run: yarn linters

  deploy:
    needs: [dependencies, build]
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.11.0'

    - run: yarn install
    
    - name: start deploy
      run: yarn deploy
    
    


