name: Test
on:
  push:
    branches: main
    
jobs:
  dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    
    steps: 
    - name: checkout code
      uses: actions/checkout@v3

    - name: install Node.js
      uses: actions/setup-node@v4
      with:
        cache: 'yarn'

    - run: yarn install

  build:
    needs: dependencies
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: install Node.js
      uses: actions/setup-node@v4

    - name: build
      run: yarn build

  linters:
    needs: dependencies
    name: linters
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: install Node.js
      uses: actions/setup-node@v4

    
    - name: start linters
      run: yarn linters

  deploy:
    needs: [dependencies, build]
    name: deploy
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: install Node.js
      uses: actions/setup-node@v4
    
    - name: start deploy
      run: yarn deploy
    
    


